<?php require '__header.phtml'; ?>
<?php require '__content.phtml'; ?>
<?php require '__menu.phtml'; ?>
<div class="row">
    <div class="col-md-2">&nbsp;</div>
    <div class="col-md-8">
        <div class="row space-16">&nbsp;</div>
        <div class="row">
            <?php foreach ($images as $key => $image): ?>
                <div class="col-sm-4">
                    <div class="thumbnail">
                        <div class="caption text-center">
                            <div class="position-relative">
                                <?php echo '<img src="/gallery/' . $image . '" style="width:100%;height:100%;"/>'; ?>
                            </div>
                        </div>
                        <div class="caption card-footer text-center">
                            <ul class="list-inline">
                                <li><i class="people lighter"></i>&nbsp;<?php echo $image; ?></li>
                                <li></li>
                                <?php if (strpos($image, "filter") !== 0): ?>
                                    <li>
                                        <?php echo '<a href="/filter?image=' . $image . '">Filter</a>'; ?> |
                                        <?php echo '<a href="/crop?image=' . $image . '">Crop</a>'; ?>
                                    </li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="col-md-2">&nbsp;</div>
    </div>
</div>
<?php require '__footer.phtml'; ?>
<?php require '__end.phtml'; ?>
