<?php require '__header.phtml'; ?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.js"></script>
<?php require '__content.phtml'; ?>
<?php require '__menu.phtml'; ?>

<div class="row">
    <div class="col-md-2">&nbsp;</div>
    <div class="col-md-8">
        <div class="row space-16">&nbsp;</div>
        <div class="row">
            <form action="/upload" class="dropzone" id="dropzoneFrom">
            </form>
        </div>
    </div>
</div>

<?php require '__footer.phtml'; ?>
<script>
    $(document).ready(function () {

        Dropzone.options.dropzoneFrom = {
            autoProcessQueue: false,
            acceptedFiles: ".png,.jpg,.gif,.bmp,.jpeg",
            init: function () {
                var submitButton = document.querySelector('#submit-all');
                myDropzone = this;
                submitButton.addEventListener("click", function () {
                    myDropzone.processQueue();
                });
                this.on("complete", function () {
                    if (this.getQueuedFiles().length == 0 && this.getUploadingFiles().length == 0) {
                        var _this = this;
                        _this.removeAllFiles();
                    }
                    list_image();
                });
            },
        };

        list_image();

        function list_image() {
            $.ajax({
                url: "/upload",
                success: function (data) {
                    $('#preview').html(data);
                }
            });
        }

        $(document).on('click', '.remove_image', function () {
            var name = $(this).attr('id');
            $.ajax({
                url: "/upload",
                method: "POST",
                data: {name: name},
                success: function (data) {
                    list_image();
                }
            })
        });

    });
</script>
<?php require '__end.phtml'; ?>
